### ISSUE TITLE
Redraw window outlines when moving them

### ISSUE THREAD

**Issue by Raniconduh** [CorruptedByCPU/Cyjon#108]
This is a pretty cool project and after playing around with it for a few minutes, I noticed that when moving a window, the entire window is redrawn until the cursor is let go of. I recommend instead for the good old windows 95 approach of only drawing the window outlines when moving them. I think this will make it faster and smoother.

**Comment by Blackend** [comment]
This is rather an option as the performance of the entire drawing system is above average.
For comparison, check out Menuet (turn off transparency) or Kolibri.

#64 First I have to rewrite the transparent window handling system, because the "frame" is a transparent window with only edges ;)

But yes, there will be a plan to handle moving windows this way. I just need time.
